name: model  # Or any name you prefer for the environment
channels:
  - conda-forge #  Important to include conda-forge for a wider range of packages
dependencies:
  - python=3.13.3 
  - pip
  - python-dotenv=1.1.0
  - anthropic